#!/usr/bin/perl
#
# cpanspec - Generate a spec file for a CPAN module
# cpan2spec - cpanspec for openruyi
#
# Copyright (C) 2004-2009 Steven Pritchard <steve@kspei.com>
# Copyright (C) 2025 openRuyi
# This program is free software; you can redistribute it
# and/or modify it under the same terms as Perl itself.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
#
# $Id: cpanspec,v 1.67 2009/01/16 20:35:17 stevenpritchard Exp $

our $NAME="cpan2spec";
our $VERSION='1.79';

=head1 NAME

cpan2spec - Generate a spec file for a CPAN module

=head1 SYNOPSIS

cpan2spec [options] [file [...]]

 Options:
   --help       -h      Help message
   --old        -o      Be more compatible with old RHL/FC releases
   --license    -l      Include generated license texts if absent in source
   --noprefix   -n      Don't add perl- prefix to package name
   --force      -f      Force overwriting existing spec
   --release    -r      Release of package (defaults to 1)
   --epoch      -e      Epoch of package
   --disttag    -d      Disttag (defaults to %{?dist})
   --srpm       -s      Build a source rpm
   --build      -b      Build source and binary rpms
   --cpan       -c      CPAN mirror URL
   --verbose    -v      Be more verbose
   --prefer-macros  -m  Prefer macros over environment variables in the spec
    --library-perl-mode     Enable writing spec files into ./library-perl (default: on)
    --no-library-perl-mode  Disable writing into ./library-perl; write to CWD
    --library-perl-dir DIR  Custom directory for spec output (default: library-perl)
    --cleanup-source        Remove downloaded source archive after generation (default: on)
    --no-cleanup-source     Keep downloaded source archive
    --no-postprocess -x     Skip buildsystem post-processing

 Long options:
   --follow             Process build dependencies
   --filter-requires    Specify Requires to remove
   --filter-provides    Specify Provides to remove
   --add-requires       Add Requires for this item
   --add-provides       Add Provides for this item
   --add-buildrequires  Add BuildRequires for this item
   --version            Print the version number and exit

=head1 DESCRIPTION

B<cpanspec> will generate a spec file to build a rpm from a CPAN-style
Perl module distribution.

=head1 OPTIONS

=over 4

=item B<-h>, B<--help>

Print a brief help message and exit.

=item B<-o>, B<--old>

Be more compatible with old RHL/FC releases.  With this option enabled,
the generated spec file

=over 4

=item *

Defines perl_vendorlib or perl_vendorarch.

=item *

Includes explicit dependencies for core Perl modules.

=item *

Uses C<%check || :> instead of just C<%check>.

=item *

Includes a hack to remove LD_RUN_PATH from Makefile.

=back

=item B<-l>, B<--license>

Generate COPYING and Artistic license texts if the source doesn't seem
to include them.

=item B<-n>, B<--noprefix>

Don't add I<perl-> prefix to the name of the package.  This is useful
for perl-based applications (such as this one), so that the name of
the rpm is simply B<cpanspec> instead of B<perl-cpanspec>.

=item B<-f>, B<--force>

Force overwriting an existing spec file.  Normally B<cpanspec> will
refuse to overwrite an existing spec file for safety.  This option
removes that safety check.  Please use with caution.

=item B<-r>, B<--release>

The release number of the package.  Defaults to 1.

=item B<-e>, B<--epoch>

The epoch number of the package.  By default, this is undefined, so
no epoch will be used in the generated spec.

=item B<-d>, B<--disttag>

Disttag (a string to append to the release number), used to
differentiate builds for various releases.  Defaults to the
blank string.

=item B<-s>, B<--srpm>

Build a source rpm from the generated spec file.

=item B<-b>, B<--build>

Build source and binary rpms from the generated spec file.
B<Please be aware that this is likely to fail!>  Even if it succeeds,
the generated rpm will almost certainly need some work to make
rpmlint happy.

=item B<-c>, B<--cpan>

The URL to a CPAN mirror.  If not specified with this option or the
B<CPAN> environment variable, defaults to L<http://www.cpan.org/>.

=item B<-u>, B<--updatepkg>

Update the package info from L<http://www.cpan.org/>.

=item B<-v>, B<--verbose>

Be more verbose.

=item B<-m>, B<--prefer-macros>

Prefer the macro form of common spec constructs over the environment variable
form (e.g. %{buildroot} vs $RPM_BUILD_ROOT).

=item B<--follow>

Add build dependencies to the list of modules to process.

=item B<--filter-requires>

Specify Requires to remove.

=item B<--filter-provides>

Specify Provides to remove.

=item B<--add-requires>

Add Requires for this item.

=item B<--add-provides>

Add Provides for this item.

=item B<--add-buildrequires>

Add BuildRequires for this item.

=item B<--version>

Print the version number and exit.

=item B<-x>, B<--no-postprocess>

Skip spec post-processing. With this option, B<cpan2spec> writes the
original generated spec and does not apply buildsystem conversion or section
omission rules.

=back

=head1 AUTHOR

Steven Pritchard <steve@kspei.com>
Xin Liu <liuxin@iscas.ac.cn>

=head1 SEE ALSO

L<perl(1)>, L<cpan2rpm(1)>, L<cpanflute2(1)>

=cut

use strict;
use warnings;

use FileHandle;
use Archive::Tar;
use Archive::Zip qw(:ERROR_CODES);
use POSIX;
use locale;
use Text::Autoformat;
use YAML qw(Load);
use Getopt::Long;
use Pod::Usage;
use File::Basename;
use LWP::UserAgent;
use Parse::CPAN::Packages;
use Pod::Simple::TextContent;
use Digest::SHA;
# Apparently gets pulled in by another module.
#use Cwd;

our %opt;

our $help=0;
our $compat=0;
our $addlicense=0;
our $noprefix=0;
our $force=0;
our $release=1;
our $epoch;
our $disttag='%{?dist}';
our $buildsrpm=0;
our $buildrpm=0;
our $verbose=0;
our $follow=0;
our $macros=1;
our $use_outdir=1;            # default: write specs under library-perl
our $outdir='library-perl';   # default output dir
our $cleanup_source=1;        # default: remove downloaded source archives
our $skip_postprocess=0;      # default: enable spec post-processing
our $source;
our $cpan=$ENV{'CPAN'} || "http://www.cpan.org";

our $home=$ENV{'HOME'} || (getpwuid($<))[7];
die "Can't locate home directory.  Please define \$HOME.\n"
    if (!defined($home));

our $pkgdetails="$home/.cpan/sources/modules/02packages.details.txt.gz";
our $updated=0;

our $packages;

our @filter_requires;
our @filter_provides;
our @add_requires;
our @add_provides;
our @add_buildrequires;

# env. vars and their macro analogues
my @MACROS = (

    # 0 is for the full expansions....
    {
        'optimize'  => '$RPM_OPT_FLAGS',
        'buildroot' => '$RPM_BUILD_ROOT',
    },

    # 1 is for the macros.
    {
        'optimize'  => '%{optflags}',
        'buildroot' => '%{buildroot}',
    },
);

# this is set after the parameters are passed
our %macro;

sub print_version {
    print "$NAME version $VERSION\n";
    exit 0;
}

sub verbose(@) {
    print STDERR @_, "\n" if ($verbose);
}

sub fetch($$) {
    my ($url, $file)=@_;
    my @locations=();

    verbose("Fetching $file from $url...");

    my $ua=LWP::UserAgent->new('env_proxy' => 1)
        or die "LWP::UserAgent->new() failed: $!\n";

    my $request;
    LOOP: $request=HTTP::Request->new('GET' => $url)
        or die "HTTP::Request->new() failed: $!\n";

    my @buf=stat($file);
    $request->if_modified_since($buf[9]) if (@buf);

    # FIXME - Probably should do $ua->request() here and skip loop detection.
    my $response=$ua->simple_request($request)
        or die "LWP::UserAgent->simple_request() failed: $!\n";

    push(@locations, $url);
    if ($response->code eq "301" or $response->code eq "302") {
        $url=$response->header('Location');
        die "Redirect loop detected! " . join("\n ", @locations, $url) . "\n"
            if (grep { $url eq $_ } @locations);
        goto LOOP;
    }

    if ($response->is_success) {
        my $fh=new FileHandle ">$file"
            or die "Can't write to $file: $!\n";
        print $fh $response->content;
        $fh->close();

        my $last_modified=$response->last_modified;
        utime(time, $last_modified, $file) if ($last_modified);
    } elsif ($response->code eq "304") {
        verbose("$file is up to date.");
    } else {
        die "Failed to get $url: " . $response->status_line . "\n";
    }
}

sub mkdir_p($) {
    my $dir=shift;

    # Handle both absolute and relative paths safely.
    my @parts = split '/', $dir;
    my $is_abs = ($dir =~ m{^/});
    my $partial = $is_abs ? '' : '.';

    for my $seg (@parts) {
        next if ($seg eq '' || $seg eq '.');
        $partial = ($partial eq '' && $is_abs) ? "/$seg" : "$partial/$seg";
        if (!-d $partial) {
            verbose("mkdir($partial)");
            mkdir $partial or die "mkdir($partial) failed: $!\n";
        }
    }
}

sub update_packages() {
    return 1 if ($updated);

    verbose("Updating $pkgdetails...");

    mkdir_p(dirname($pkgdetails)) if (!-d dirname($pkgdetails));

    my $is_valid_pkgdetails = sub {
        my ($file)=@_;
        return 0 if (!-f $file);

        my $ok = system('gzip', '-t', $file);
        return ($ok == 0) ? 1 : 0;
    };

    # If cached index is corrupt, remove it so fetch cannot return 304.
    if (-f $pkgdetails and !$is_valid_pkgdetails->($pkgdetails)) {
        warn "Cached package index is corrupt, removing: $pkgdetails\n";
        unlink $pkgdetails or die "Failed to remove corrupt $pkgdetails: $!\n";
    }

    my $index_url = "$cpan/modules/" . basename($pkgdetails);
    my $attempts = 0;
    while ($attempts < 2) {
        $attempts++;
        fetch($index_url, $pkgdetails);
        last if ($is_valid_pkgdetails->($pkgdetails));

        warn "Downloaded package index appears truncated/corrupt (attempt $attempts): $pkgdetails\n";
        unlink $pkgdetails;
    }

    die "Failed to fetch a valid CPAN package index from $index_url\n"
        if (!$is_valid_pkgdetails->($pkgdetails));

    $updated=1;
}

sub build_rpm($) {
    my $spec=shift;
    my $dir=getcwd();

    my $rpmbuild=(-x "/usr/bin/rpmbuild" ? "/usr/bin/rpmbuild" : "/bin/rpm");

    verbose("Building " . ($buildrpm ? "rpms" : "source rpm") . " from $spec");

    # From Fedora CVS Makefile.common.
    if (system($rpmbuild, "--define", "_sourcedir $dir",
                          "--define", "_builddir $dir",
                          "--define", "_srcrpmdir $dir",
                          "--define", "_rpmdir $dir",
                          ($buildrpm ? "-ba" : ("-bs", "--nodeps")),
                          $spec) != 0) {
        if ($? == -1) {
            die "Failed to execute $rpmbuild: $!\n";
        } elsif (WIFSIGNALED($?)) {
            die "$rpmbuild died with signal " . WTERMSIG($?)
                . (($? & 128) ? ", core dumped\n" : "\n");
        } else {
            die "$rpmbuild exited with value " . WEXITSTATUS($?) . "\n";
        }
    }
}

sub list_files($$) {
    my $archive=$_[0];
    my $type=$_[1];

    if ($type eq 'tar') {
        return $archive->list_files();
    } elsif ($type eq 'zip') {
        return map { $_->fileName(); } $archive->members();
    }
}

sub extract($$$) {
    my $archive=$_[0];
    my $type=$_[1];
    my $filename=$_[2];

    if ($type eq 'tar') {
        return $archive->get_content($filename);
    } elsif ($type eq 'zip') {
        return $archive->contents($filename);
    }
}

sub get_description(%) {
    my %args=@_;
    my $pm="";
    my ($summary, $description);

    my $path=$args{module};
    $path=~s,::,/,g;
    my @pmfiles=("$args{path}/lib/$path.pod",
        "$args{path}/lib/$path.pm");
    if ($args{module} =~ /::/) {
        my @tmp=split '/', $path;
        my $last=pop @tmp;
        push(@pmfiles, "$args{path}/lib/$last.pod",
            "$args{path}/lib/$last.pm");
    }
    do {
        push(@pmfiles, "$args{path}/$path.pod",
            "$args{path}/$path.pm");
    } while ($path=~s,^[^/]+/,,);
    push(@pmfiles, "$args{path}/$args{module}")
        if ($args{module} !~ /::/);

    for my $file (@pmfiles) {
        $pm=(grep { $_ eq $file or $_ eq "./$file" }
            list_files($args{archive}, $args{type}))[0];
        last if $pm;
    }

    if ($pm) {
        verbose "Trying to fetch description from $pm...";

        if (my $content=extract($args{archive}, $args{type}, $pm)) {
            my $parser=Pod::Simple::TextContent->new()
                or die "Pod::Simple::TextContent->new() failed: $!\n";
            $parser->no_whining(1);
            my $rendered="";
            $parser->output_string(\$rendered);
            $parser->parse_string_document($content);
            if ($parser->content_seen and $rendered) {
                if ($rendered=~/DESCRIPTION\s+(\S.*?)\n\n/s) {
                    $description=$1;
                }
                if ($rendered=~/NAME\s*$args{module}\s[-\s]*(\S[^\n]*)/s) {
                    if ($1 ne "SYNOPSIS") {
                        $summary=$1;
                        $summary=~s/[.\s]+$//;
                        $summary=~s/^(?:An?|The)\s+//i;
                        $summary=ucfirst($summary);
                    }
                }
                return($description, $summary) if (defined($description));
            }
        } else {
            warn "Failed to read $pm from $args{filename}"
                . ($args{type} eq 'tar'
                    ? (": " . $args{archive}->error()) : "") . "\n";
        }
    }

    if (my $readme=(sort {
                        length($a) <=> length($b) or $a cmp $b
                     } (grep /README/i, @{$args{files}}))[0]) {
        verbose "Trying to fetch description from $readme...";

        if (my $content=extract($args{archive}, $args{type},
                "$args{path}/$readme")) {
            $content=~s/\r//g; # Why people use DOS text, I'll never understand.
            for my $string (split "\n\n", $content) {
                $string=~s/^\n+//;
                if ((my @tmp=split "\n", $string) > 2
                    and $string !~ /^[#\-=]/) {
                    return($string, undef);
                }
            }
        } else {
            warn "Failed to read $readme from $args{filename}"
                . ($args{type} eq 'tar'
                    ? (": " . $args{archive}->error()) : "") . "\n";
        }
    }

    return(undef, undef);
}

sub check_rpm($) {
    my $dep=shift;

    my $rpm="/bin/rpm";
    return undef if (!-x $rpm);

    my @out=`$rpm -q --whatprovides "$dep"`;

    if ($? != 0) {
        #warn "backtick (rpm) failed with return value $?";
        return undef;
    }

    return @out;
}

sub check_repo($) {
    my $dep=shift;

    my ($repoquery, $repoqueryopts);
    if (-x ($repoquery = '/usr/bin/dnf')) {
        $repoqueryopts = "repoquery --whatprovides '${dep}'"
    } elsif (-x ($repoquery = '/usr/bin/repoquery')) {
        $repoqueryopts = "--whatprovides '${dep}'"
    } else {
        return undef
    }

    verbose("Running $repoquery to check for $dep.  This may take a while...");
    my @out=`$repoquery $repoqueryopts 2>/dev/null`;

    if ($? != 0) {
        #warn "backtick (repoquery) failed with return value $?";
        return undef;
    }

    return grep { /^\S+-[^-]+-[^-]+$/ } @out;
}

sub check_dep($) {
    my $module=shift;

    return (check_rpm("perl($module)") || check_repo("perl($module)"));
}

# calculate the SHA256 of a file, returning a string of 64 zeros if the file doesn't exist or an error occurs
sub get_sha256($) {
    my $file=shift;

    return "0" x 64 if (!-f $file);

    open my $fh, '<', $file
        or die "Can't open $file: $!\n";

    binmode $fh;

    my $sha256 = Digest::SHA->new(256)
                    ->addfile($fh)
                    ->hexdigest;

    return $sha256 || ("0" x 64);
}


sub refine_license_from_files(%) {
    my %args=@_;
    my $archive=$args{archive};
    my $type=$args{type};
    my $path=$args{path};
    my $current=$args{current} || '';
    my @files=@{$args{files} || []};
    my @license_files=@{$args{license_files} || []};

    # Keep the original META.yml license parser above this function.  This
    # routine is only a second pass over files that are actually shipped in the
    # CPAN source archive.  It is intentionally small and conservative:
    #
    #   * First read explicit license files such as LICENSE, COPYING, ARTISTIC
    #     and GPL*.  These files are the strongest evidence.
    #   * If there is no explicit license file, read a few common documentation
    #     files (README, Changes, .pm, .pod) because old CPAN modules often put
    #     "same terms as Perl" only in POD.
    #   * Do not scan tests or every file in the archive.  That avoids mixing in
    #     unrelated license text from test data or bundled examples.
    #   * Only replace an already specific META.yml result when the file gives a
    #     clearly better answer, such as Artistic-2.0 instead of old metadata
    #     value "artistic".

    my @scan_files = @license_files;

    if (!@scan_files) {
        push @scan_files, grep {
               !m{/(?:t|xt|inc|blib)/}
            && (
                   $_ =~ /^(?:README|README\.md|README\.txt)$/i
                || $_ =~ /^(?:Changes|ChangeLog)$/i
                || $_ =~ m{^(?:lib/)?[^/]+(?:/[^/]+)*\.(?:pm|pod)$}i
               )
        } @files;
    }

    my @detected;
    my %seen;

    for my $file (@scan_files) {
        my $text=extract($archive, $type, "$path/$file");
        next if (!defined($text) or $text eq '');

        my $sample=substr($text, 0, 262144);
        $sample =~ s/\r/\n/g;

        my @found;
        my %found_seen;
        my $saw_dual=0;
        my $add = sub {
            my $license=shift;
            return if (!defined($license) or $license eq '');
            return if ($found_seen{$license}++);
            push @found, $license;
        };

        # "same terms as Perl" is the usual CPAN shorthand for Perl's dual
        # license: GPL-1.0-or-later OR Artistic-1.0-Perl.
        if ($sample =~ /same terms as (?:perl|the perl programming language|perl itself)/i) {
            $add->('GPL-1.0-or-later OR Artistic-1.0-Perl');
            $saw_dual=1;
        }

        # Some files spell out "GPL or Artistic".  Keep GPL and Artistic version
        # detection separate.  For example, B::Keywords says GPL version 2, but
        # the Artistic license is "which comes with Perl", not Artistic 2.0.
        if ($sample =~ /(?:GNU\s+(?:GENERAL\s+)?PUBLIC\s+LICENSE|GNU\s+public\s+license)/i
            and $sample =~ /Artistic License/i
            and ($sample =~ /under the terms of either/i
                 or $sample =~ /terms of either/i
                 or $sample =~ /which comes with Perl/i
                 or $sample =~ /or\s+(?:the\s+)?Artistic License/i
                 or $sample =~ /Artistic License.*?or.*?(?:GNU\s+)?(?:General\s+)?Public License/is
                 or $sample =~ /(?:GNU\s+)?(?:General\s+)?Public License.*?or.*?Artistic License/is)) {
            my $gpl='GPL-1.0-or-later';
            my $artistic='Artistic-1.0-Perl';

            if ($sample =~ /any version/i) {
                $gpl='GPL-1.0-or-later';
            } elsif ($sample =~ /(?:GNU\s+(?:GENERAL\s+)?PUBLIC\s+LICENSE|GNU\s+public\s+license).*?version\s+3/is) {
                $gpl = ($sample =~ /or\s+(?:any\s+)?later\s+version/i) ? 'GPL-3.0-or-later' : 'GPL-3.0-only';
            } elsif ($sample =~ /(?:GNU\s+(?:GENERAL\s+)?PUBLIC\s+LICENSE|GNU\s+public\s+license).*?version\s+2/is) {
                $gpl = ($sample =~ /or\s+(?:any\s+)?later\s+version/i) ? 'GPL-2.0-or-later' : 'GPL-2.0-only';
            } elsif ($sample =~ /(?:GNU\s+(?:GENERAL\s+)?PUBLIC\s+LICENSE|GNU\s+public\s+license).*?version\s+1/is) {
                $gpl = ($sample =~ /or\s+(?:any\s+)?later\s+version/i) ? 'GPL-1.0-or-later' : 'GPL-1.0-only';
            }

            if ($sample =~ /Artistic License\s+2(?:\.0)?/i
                or $sample =~ /Artistic License.*?Version\s+2(?:\.0)?/is
                or $sample =~ /Artistic License.*?\bv2(?:\.0)?\b/is) {
                $artistic='Artistic-2.0';
            }
            if ($sample =~ /Artistic License["']?\s+which comes with Perl/i) {
                $artistic='Artistic-1.0-Perl';
            }

            $add->("$gpl OR $artistic");
            $saw_dual=1;
        }

        if ($sample =~ /Apache License/i and $sample =~ /Version\s+2\.0/i) {
            $add->('Apache-2.0');
        }
        if ($sample =~ /\bMIT License\b/i
            or $sample =~ /Permission is hereby granted,\s+free of charge,\s+to any person obtaining a copy/i) {
            $add->('MIT');
        }
        if ($sample =~ /\bISC License\b/i
            or $sample =~ /Permission to use,\s+copy,\s+modify,\s+and\/or distribute this software for any purpose with or without fee/i) {
            $add->('ISC');
        }

        # Check LGPL before GPL.  Also avoid a false LGPL hit from the standard
        # GPL text, which mentions the Lesser GPL only in passing.
        if (!$saw_dual and ($sample =~ /^\s*GNU LESSER GENERAL PUBLIC LICENSE/im
            or ($sample =~ /Lesser General Public License\s*\(LGPL\)/i
                and $sample !~ /^\s*GNU GENERAL PUBLIC LICENSE/im))) {
            if ($sample =~ /Version\s+3/i) {
                $add->(($sample =~ /or\s+(?:any\s+)?later\s+version/i) ? 'LGPL-3.0-or-later' : 'LGPL-3.0-only');
            } elsif ($sample =~ /Version\s+2\.1/i) {
                $add->(($sample =~ /or\s+(?:any\s+)?later\s+version/i) ? 'LGPL-2.1-or-later' : 'LGPL-2.1-only');
            } elsif ($sample =~ /Version\s+2/i) {
                $add->(($sample =~ /or\s+(?:any\s+)?later\s+version/i) ? 'LGPL-2.0-or-later' : 'LGPL-2.0-only');
            } else {
                $add->('LGPL-2.0-or-later');
            }
        }

        if (!$saw_dual and ($sample =~ /^\s*GNU GENERAL PUBLIC LICENSE/im
            or $sample =~ /GNU\s+public\s+license/i)) {
            my $is_full_gpl_text = ($sample =~ /^\s*GNU GENERAL PUBLIC LICENSE/im);

            # A full GPL license text contains explanatory wording about how
            # "or later" works, but that does not by itself grant this package
            # an "or later" license.  Only package-level wording should upgrade
            # a concrete GPL version to "-or-later".
            my $has_package_or_later =
                (!$is_full_gpl_text
                 and ($sample =~ /or\s+(?:any\s+)?later\s+version/i
                      or $sample =~ /any version/i));

            if ($sample =~ /Version\s+3/i) {
                $add->($has_package_or_later ? 'GPL-3.0-or-later' : 'GPL-3.0-only');
            } elsif ($sample =~ /Version\s+2/i) {
                $add->($has_package_or_later ? 'GPL-2.0-or-later' : 'GPL-2.0-only');
            } elsif ($sample =~ /Version\s+1/i) {
                $add->($has_package_or_later ? 'GPL-1.0-or-later' : 'GPL-1.0-only');
            } elsif ($sample =~ /any version/i) {
                $add->('GPL-1.0-or-later');
            } else {
                $add->('GPL-1.0-or-later');
            }
        }

        if (!$saw_dual and $sample =~ /Artistic License/i) {
            if ($sample =~ /Artistic License\s+2(?:\.0)?/i
                or $sample =~ /The\s+Artistic\s+License\s+2(?:\.0)?/i
                or $sample =~ /Artistic License.*?\bv2(?:\.0)?\b/is) {
                $add->('Artistic-2.0');
            } else {
                $add->('Artistic-1.0-Perl');
            }
        }

        if ($sample =~ /Mozilla Public License/i) {
            if ($sample =~ /Version\s+2\.0/i) {
                $add->('MPL-2.0');
            } elsif ($sample =~ /Version\s+1\.1/i) {
                $add->('MPL-1.1');
            } elsif ($sample =~ /Version\s+1\.0/i) {
                $add->('MPL-1.0');
            }
        }
        
        if ($sample =~ /Redistribution and use in source and binary forms/i
            and $sample =~ /THIS SOFTWARE IS PROVIDED/i) {
            $add->('BSD');
        }

        # If content matching did not fire, use very explicit license file names
        # as a last resort.  GPL2.txt in CPAN distributions usually means the
        # package offers GPLv2-or-later as one choice, but a full GPLv2 COPYING
        # text without package-level "or later" wording remains GPL-2.0-only.
        if (!@found) {
            my $base=basename($file);
            if ($base =~ /^ARTISTIC.*2/i) {
                $add->('Artistic-2.0');
            } elsif ($base =~ /^ARTISTIC/i) {
                $add->('Artistic-1.0-Perl');
            } elsif ($base =~ /LGPL.*3/i) {
                $add->('LGPL-3.0-or-later');
            } elsif ($base =~ /LGPL.*2[._-]?1/i) {
                $add->('LGPL-2.1-or-later');
            } elsif ($base =~ /LGPL.*2/i) {
                $add->('LGPL-2.0-or-later');
            } elsif ($base =~ /GPL.*3/i) {
                $add->('GPL-3.0-or-later');
            } elsif ($base =~ /GPL.*2/i) {
                $add->('GPL-2.0-or-later');
            } elsif ($base =~ /^GPL/i) {
                $add->('GPL-1.0-or-later');
            }
        }

        # A standard GPL text may mention the Artistic license only because it
        # is bundled with another file in the distribution.  Keep each explicit
        # license file's own result; later we join the unique results from all
        # explicit license files with OR.
        for my $license (@found) {
            next if (!$license);
            next if ($seen{$license}++);
            push @detected, $license;
        }
    }

    my $from_files=join(' OR ', @detected);

    if ($from_files) {
        return $from_files
            if (!$current
                or $current =~ /^CHECK\(/
                or $current =~ /^(?:any-OSI|Distributable|Non-distributable)(?:,|$)/
                or ($current eq 'Artistic-1.0-Perl' and $from_files =~ /^Artistic-2\.0\b/)
                or ($current eq 'GPL-1.0-or-later' and $from_files =~ /^GPL-\d+(?:\.\d+)?-(?:only|or-later)$/));
    }

    return 'CHECK(GPL-1.0-or-later OR Artistic-1.0-Perl)'
        if (!$current or $current eq 'CHECK(Distributable)');

    return $current;
}

sub section_bounds($$) {
    my ($lines, $section)=@_;

    my $is_section_header = sub {
        my ($line)=@_;
        return ($line =~ /^%(?:description|prep|build|install|check|files|changelog|package|pre|post|preun|postun|posttrans|trigger(?:in|un|postun)?|verifyscript)\b/);
    };

    my $start;
    for (my $i=0; $i<@{$lines}; $i++) {
        if ($lines->[$i] =~ /^\Q$section\E\b/) {
            $start=$i;
            last;
        }
    }
    return (undef, undef) if (!defined($start));

    my $end=@{$lines};
    for (my $i=$start+1; $i<@{$lines}; $i++) {
        if ($is_section_header->($lines->[$i])) {
            $end=$i;
            last;
        }
    }

    return ($start, $end);
}

sub trimmed_section_lines($$) {
    my ($lines, $section)=@_;
    my ($start, $end)=section_bounds($lines, $section);
    return () if (!defined($start));

    my @body=@{$lines}[$start+1 .. $end-1];
    while (@body and $body[0] =~ /^\s*$/) {
        shift @body;
    }
    while (@body and $body[$#body] =~ /^\s*$/) {
        pop @body;
    }

    return @body;
}

sub is_default_perlmaker_install {
    my @lines=@_;

    return 0 if (@lines < 3 or @lines > 4);
    return 0 if ($lines[0] ne '%perl_make_install');
    return 0 if ($lines[$#lines] ne '%perl_gen_filelist');

    if (@lines == 3) {
        return ($lines[1] eq '%perl_process_packlist') ? 1 : 0;
    }

    return 0 if ($lines[1] ne "find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \\;");
    return ($lines[2] eq '%perl_process_packlist') ? 1 : 0;
}

sub is_default_perlbuild_install {
    my @lines=@_;

    return 0 if (@lines < 2 or @lines > 4);
    return 0 if ($lines[0] !~ m{^\./Build install (?:--)?destdir=%\{buildroot\} (?:--)?create_packlist=0$});
    return 0 if ($lines[$#lines] ne '%perl_gen_filelist');

    if (@lines == 2) {
        return 1;
    }

    if (@lines == 3) {
        return ($lines[1] eq '%perl_process_packlist') ? 1 : 0;
    }

    return 0 if ($lines[1] ne "find %{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \\;");
    return ($lines[2] eq '%perl_process_packlist') ? 1 : 0;
}

sub normalize_perlbuild_install_options {
    my $opts=shift;

    $opts =~ s/(^|\s)destdir=/$1--destdir=/g;
    $opts =~ s/(^|\s)create_packlist=/$1--create_packlist=/g;

    return $opts;
}

sub collapse_blank_lines($) {
    my ($lines)=@_;

    my @out;
    my $blank_count=0;
    for my $line (@{$lines}) {
        if ($line =~ /^\s*$/) {
            $blank_count++;
            next if ($blank_count > 2);
        } else {
            $blank_count=0;
        }
        push @out, $line;
    }

    @{$lines}=@out;
}

sub postprocess_spec($) {
    my $specfile=shift;

    my $in=new FileHandle $specfile, 'r'
        or die "Failed to open $specfile for reading: $!\n";
    local $/=undef;
    my $content=<$in>;
    $in->close();

    my @lines=split /\n/, $content;

    my @build_lines=trimmed_section_lines(\@lines, '%build');
    my @install_lines=trimmed_section_lines(\@lines, '%install');

    my $buildsystem='';
    my @build_options;
    my @install_options;
    my $omit_build=0;
    my $omit_install=0;

    my $perlmaker_build_ok = (
        @build_lines >= 2
        and $build_lines[0] =~ /^perl Makefile\.PL INSTALLDIRS=vendor(?: OPTIMIZE="%\{optflags\}")?$/
        and $build_lines[1] eq '%{make_build}'
    );
    my $perlbuild_build_ok = (
        @build_lines >= 2
        and $build_lines[0] =~ /^perl Build\.PL --installdirs=vendor(?: optimize="%\{optflags\}")?$/
        and $build_lines[1] eq './Build'
    );

    if ($perlmaker_build_ok) {
        $buildsystem='perlmaker';
        $omit_build=1;
        if ($build_lines[0] =~ /^perl Makefile\.PL\s+(.+)$/) {
            push @build_options, $1;
        }
        $omit_install = is_default_perlmaker_install(@install_lines) ? 1 : 0;
    } elsif ($perlbuild_build_ok) {
        $buildsystem='perlbuild';
        $omit_build=1;
        if ($build_lines[0] =~ /^perl Build\.PL\s+(.+)$/) {
            push @build_options, $1;
        }
        if (@install_lines and $install_lines[0] =~ m{^\./Build install\s+(.+)$}) {
            push @install_options, normalize_perlbuild_install_options($1);
        }
        $omit_install = is_default_perlbuild_install(@install_lines) ? 1 : 0;
    } else {
        if (@build_lines and $build_lines[0] =~ /^perl Makefile\.PL\b/) {
            $buildsystem='perlmaker';
            if ($build_lines[0] =~ /^perl Makefile\.PL\s+(.+)$/) {
                push @build_options, $1;
            }
        } elsif (@build_lines and $build_lines[0] =~ /^perl Build\.PL\b/) {
            $buildsystem='perlbuild';
            if ($build_lines[0] =~ /^perl Build\.PL\s+(.+)$/) {
                push @build_options, $1;
            }
            if (@install_lines and $install_lines[0] =~ m{^\./Build install\s+(.+)$}) {
                push @install_options, normalize_perlbuild_install_options($1);
            }
        }
    }

    # Always ensure perl-rpm-macros is in BuildRequires.
    my $has_rpm_macros = (grep { $_ =~ /^BuildRequires:\s+perl-rpm-macros\s*$/ } @lines) ? 1 : 0;
    if (!$has_rpm_macros) {
        my $insert_at;
        for (my $i=0; $i<@lines; $i++) {
            if ($lines[$i] =~ /^BuildRequires:\s+perl-rpm-packaging\s*$/) {
                $insert_at=$i+1;
                last;
            }
        }
        if (!defined($insert_at)) {
            for (my $i=0; $i<@lines; $i++) {
                if ($lines[$i] =~ /^BuildRequires:\s+/) {
                    $insert_at=$i;
                    last;
                }
            }
        }
        splice @lines, $insert_at, 0, 'BuildRequires:  perl-rpm-macros' if (defined($insert_at));
    }

    # Remove previously generated BuildSystem/BuildOption headers, then reinsert.
    @lines=grep {
        $_ !~ /^BuildSystem:\s+/ and $_ !~ /^BuildOption\(build\):\s+/ and $_ !~ /^BuildOption\(install\):\s+/
    } @lines;

    if ($buildsystem) {
        my $anchor;
        for (my $i=0; $i<@lines; $i++) {
            if ($lines[$i] =~ /^BuildArch:\s+/) {
                $anchor=$i;
                last;
            }
        }
        if (!defined($anchor)) {
            for (my $i=0; $i<@lines; $i++) {
                if ($lines[$i] =~ /^Source0:\s+/) {
                    $anchor=$i;
                    last;
                }
            }
        }

        if (defined($anchor)) {
            my @insert=('BuildSystem:    ' . $buildsystem);
            if (@build_options or @install_options) {
                push @insert, '';
            }
            for my $opt (@build_options) {
                next if (!defined($opt) or $opt eq '');
                push @insert, 'BuildOption(build):  ' . $opt;
            }
            for my $opt (@install_options) {
                next if (!defined($opt) or $opt eq '');
                push @insert, 'BuildOption(install):  ' . $opt;
            }

            splice @lines, $anchor+1, 0, @insert;
        }
    }

    # %prep is always omitted.
    my ($prep_s, $prep_e)=section_bounds(\@lines, '%prep');
    splice @lines, $prep_s, $prep_e-$prep_s if (defined($prep_s));

    if ($omit_build) {
        my ($build_s, $build_e)=section_bounds(\@lines, '%build');
        splice @lines, $build_s, $build_e-$build_s if (defined($build_s));
    }
    if ($omit_install) {
        my ($install_s, $install_e)=section_bounds(\@lines, '%install');
        splice @lines, $install_s, $install_e-$install_s if (defined($install_s));
    }

    collapse_blank_lines(\@lines);

    my $out=new FileHandle ">$specfile"
        or die "Failed to open $specfile for writing: $!\n";
    print $out join("\n", @lines), "\n";
    $out->close();
}

# Set locale to en_US.UTF8 so that dates in changelog will be correct
# if using another locale. Also ensures writing out UTF8. (Thanks to
# Roy-Magne Mo for pointing out the problem and providing a solution.)
setlocale(LC_ALL, "en_US.UTF-8");

GetOptions(
        'help|h'            => \$help,
        'old|o'             => \$compat,
        'license|l'         => \$addlicense,
        'noprefix|n'        => \$noprefix,
        'force|f'           => \$force,
        'release|r=i'       => \$release,
        'epoch|e=i'         => \$epoch,
        'disttag|d=s'       => \$disttag,
        'srpm|s'            => \$buildsrpm,
        'build|b'           => \$buildrpm,
        'cpan|c=s'          => \$cpan,
        'verbose|v'         => \$verbose,
        'follow'            => \$follow,
        'filter-requires=s' => \@filter_requires,
        'filter-provides=s' => \@filter_provides,
        'add-requires=s'    => \@add_requires,
        'add-provides=s'    => \@add_provides,
        'add-buildrequires=s' => \@add_buildrequires,
        'version'           => \&print_version,
        'prefer-macros|m'   => \$macros,
    'library-perl-mode!' => \$use_outdir,
    'library-perl-dir=s' => \$outdir,
    'cleanup-source!'    => \$cleanup_source,
    'keep-source'        => sub { $cleanup_source = 0 },
    'no-postprocess|x'   => \$skip_postprocess,
    ) or pod2usage({ -exitval => 1, -verbose => 0 });

pod2usage({ -exitval => 0, -verbose => 1 }) if ($help);
pod2usage({ -exitval => 1, -verbose => 0 }) if (!@ARGV);

if ($follow and $buildrpm) {
    warn "Sorry, --follow and --build are mutually exclusive right now.\n"
        . "We can't build when tracking deps right now.  Ignoring --build.\n";
    $buildrpm=0;
}

%macro = %{ $MACROS[$macros] };

my $prefix=$noprefix ? "" : "perl-";

our %corelist;

my $rpm=new FileHandle "rpm -q --provides perl|"
    or warn "Failed to execute rpm: $!\n";

while (my $provides=<$rpm>) {
    chomp $provides;

    if ($provides=~/^perl\(([^\)]+)\)(?:\s+=\s+(\S+))\s*$/) {
        $corelist{$1}=defined($2) ? $2 : 0;
    }
}

my @args=@ARGV;
my @processed=();
my $downloaded;   # whether we fetched the archive (and can delete)

for my $file (@args) {
    my ($name,$version,$type);
    $downloaded = 0;      # reset per iteration

    if ($file =~ /^(?:.*\/)?(.*)-(?:v\.?)?([^-]+)\.(tar)\.(?:gz|bz2)$/) {
        $name=$1;
        $version=$2;
        $type=$3;
    } elsif ($file =~ /^(?:.*\/)?(.*)-(?:v\.?)?([^-]+)\.tgz$/) {
        $name=$1;
        $version=$2;
        $type = 'tar';
    } elsif ($file =~ /^(?:.*\/)?(.*)-(?:v\.?)?([^-]+)\.(zip)$/) {
        $name=$1;
        $version=$2;
        $type=$3;
    } else {

        # keep things happy if we get "Foo-Bar" instead of "Foo::Bar"
        $file =~ s/-/::/g;

        # Look up $file in 02packages.details.txt.
        update_packages();
        $packages=Parse::CPAN::Packages->new($pkgdetails)
            if (!defined($packages));
        die "Parse::CPAN::Packages->new() failed: $!\n"
            if (!defined($packages));
        my ($m,$d);
        if ($m=$packages->package($file) and $d=$m->distribution()) {
            $source=$cpan . "/authors/id/" . $d->prefix();
            $file=basename($d->filename());
            fetch($source, $file);
            $downloaded = 1;
            $name=$d->dist();
            $version=$d->version();
            $version=~s/^v\.?//;
            if ($file =~ /\.(tar)\.gz$/) {
                $type=$1;
            } elsif ($file =~ /\.tgz$/) {
                $type='tar';
            } elsif ($file =~ /\.(zip)$/) {
                $type=$1;
            } else {
                warn "Failed to parse '$file', skipping...\n";
                next;
            }
        } else {
            warn "Failed to parse '$file' or find a module by that name, skipping...\n";
            next;
        }
    }

    my $module=$name;
    $module=~s/-/::/g;

    my $sha256="";
    if ($downloaded and -f $file) {
        $sha256=get_sha256($file);
        verbose("SHA256: $sha256");
    }

    my $archive;
    my $path;
    if ($type eq 'tar') {
        my $f=$file;
        if ($file=~/\.bz2$/) {
            eval {
                use IO::Uncompress::Bunzip2;
            };

            if ($@) {
                warn "Failed to load IO::Uncompress::Bunzip2: $@\n";
                warn "Skipping $file...\n";
                next;
            }

            $f=IO::Uncompress::Bunzip2->new($file);
            if (!defined($f)) {
                warn "IO::Uncompress::Bunzip2->new() failed on $file: $!\n";
                next;
            }
        }
        $archive=Archive::Tar->new($f, 1)
            or die "Archive::Tar->new() failed: $!\n";
    } elsif ($type eq 'zip') {
        $archive=Archive::Zip->new() or die "Archive::Zip->new() failed: $!\n";
        die "Read error on $file\n" unless ($archive->read($file) == AZ_OK);
    }

    my @files;

    my $bogus=0;
    for my $entry (list_files($archive, $type)) {
        next if ($type eq 'tar' and $entry eq 'pax_global_header');

        if ($entry !~ /^(?:.\/)?($name-(?:v\.?)?$version)(?:\/|$)/) {
            warn "BOGUS PATH DETECTED: $entry\n";
            $bogus++;
            next;
        } elsif (!defined($path)) {
            $path=$1;
        }

        $entry=~s,^(?:.\/)?$name-(?:v\.?)?$version/,,;
        next if (!$entry);

        push(@files, $entry);
    }
    if ($bogus) {
        warn "Skipping $file with $bogus path elements!\n";
        next;
    }

    my $url="https://metacpan.org/dist/$name";

    $source=$source || "https://www.cpan.org/modules/by-module/"
        . ($module=~/::/ ? (split "::", $module)[0] : (split "-", $name)[0])
        . "/" . basename($file);
    $source=~s/$version/\%{version}/;

    my ($description,$summary)=get_description(
            archive     => $archive,
            type        => $type,
            filename    => $file,
            name        => $name,
            module      => $module,
            version     => $version,
            files       => \@files,
            path        => $path,
        );

    if (defined($description) and $description) {
        $description=autoformat $description, { "all"     => 1,
                                                "left"    => 1,
                                                "right"   => 75,
                                                "squeeze" => 0,
                                              };
        $description=~s/\n+$//s;
    } else {
        $description="$module Perl module";
    }

    $summary="$module Perl module" if (!defined($summary));

    my @doc=sort { $a cmp $b } grep {
                !/\//
            and !/\.(pl|xs|h|c|pm|in|pod|cfg|inl)$/i
            and !/^\./
            and $_ ne $path
            and $_ ne "MANIFEST"
            and $_ ne "MANIFEST.SKIP"
            and $_ ne "INSTALL"
            and $_ ne "SIGNATURE"
            and $_ ne "META.yml"
            and $_ ne "META.json"
            and $_ ne "NINJA"
            and $_ ne "configure"
            and $_ ne "config.guess"
            and $_ ne "config.sub"
            and $_ ne "cpanfile"
            and $_ ne "dist.ini"
            and $_ ne "typemap"
            and $_ ne "bin"
            and $_ ne "lib"
            and $_ ne "t"
            and $_ ne "inc"
            and $_ ne "autobuild.sh"
            and $_ ne "pm_to_blib"
            and $_ ne "install.sh"
            # License files
            and $_ ne "LICENSE"
            and $_ ne "LICENCE"
            and $_ ne "Copying"
            and $_ ne "COPYING"
            and $_ ne "COPYING.Artistic"
            and $_ ne "COPYING.GNU"
            and $_ ne "COPYRIGHT"
            and $_ ne "ARTISTIC.txt"
            and $_ ne "Artistic"
            and $_ ne "Artistic.txt"
            and $_ ne "GNU_GPL.txt"
            and $_ ne "GNU_LGPL.txt"
            and $_ ne "GPL"
            and $_ ne "GPLv1"
            and $_ ne "GPL2.txt"
            and $_ ne "DISCLAIMER.txt"
            } @files;

    my @license=sort { $a cmp $b } grep {
               $_ eq "LICENSE"
            or $_ eq "LICENCE"
            or $_ eq "Copying"
            or $_ eq "COPYING"
            or $_ eq "COPYING.Artistic"
            or $_ eq "COPYING.GNU"
            or $_ eq "COPYRIGHT"
            or $_ eq "ARTISTIC.txt"
            or $_ eq "Artistic"
            or $_ eq "Artistic.txt"
            or $_ eq "GNU_GPL.txt"
            or $_ eq "GNU_LGPL.txt"
            or $_ eq "GPL"
            or $_ eq "GPLv1"
            or $_ eq "GPL2.txt"
            or $_ eq "DISCLAIMER.txt"
            } @files;

    my $date=strftime("%a %b %d %Y", localtime);

    # Determine whether this is an architecture-independent module.
    my $noarch = 1;
    # If there are any C files, XS files, or .ucm files, it's not noarch.
    $noarch = 0 if grep /\.(c|h|xs|inl)$/i, @files;
    # .ucm files are used by Unicode::Collate
    # If there are any .ucm files, it's not noarch.
    $noarch = 0 if grep /\.ucm$/i, @files;
    # Check for enc2xs, XSLoader, or ExtUtils::ParseXS in Makefile.PL or Build.PL
    # These are used to build XS files. If found, it's not noarch.
    my @build_drivers = qw(Makefile.PL Build.PL);
    for my $drv (@build_drivers) {
        if (grep { $_ eq $drv } @files) {
            my $text = extract($archive, $type, "$path/$drv") // '';
            if ($text =~ /\benc2xs\b/i
                || $text =~ /\bXSLoader\b/
                || $text =~ /\bExtUtils::ParseXS\b/) {
                $noarch = 0;
            }
        }
    }

    # Determine which perl install path macro to use based on architecture
    # noarch modules install to vendorlib, arch-specific to vendorarch.
    my $vendorlib = $noarch ? 'vendorlib' : 'vendorarch';
    my $lib="\%{perl_$vendorlib}";

    if (@filter_requires) {
        my $script="$name-filter-requires.sh";
        verbose "Writing $script...";
        my $sh;
        if ($force) {
            rename($script, "$script~") if (-e $script);
            $sh=new FileHandle ">$script";
        } else {
            $sh=new FileHandle $script, O_WRONLY|O_CREAT|O_EXCL;
        }
        die "Failed to create $script: $!\n" if (!$sh);

        map { s/\//\\\//g } @filter_requires;
        print $sh "#!/bin/sh\n\n"
            . "\@\@PERL_REQ\@\@ \"\$\@\" | sed -e '/^$filter_requires[0]\$/d'";
        if (@filter_requires > 1) {
            for my $dep (@filter_requires[1..$#filter_requires]) {
                print $sh " \\\n    -e '/^$dep\$/d'";
            }
        }
        print $sh "\n";
    }

    if (@filter_provides) {
        my $script="$name-filter-provides.sh";
        verbose "Writing $script...";
        my $sh;
        if ($force) {
            rename($script, "$script~") if (-e $script);
            $sh=new FileHandle ">$script";
        } else {
            $sh=new FileHandle $script, O_WRONLY|O_CREAT|O_EXCL;
        }
        die "Failed to create $script: $!\n" if (!$sh);

        map { s/\//\\\//g } @filter_provides;
        print $sh "#!/bin/sh\n\n"
            . "\@\@PERL_PROV\@\@ \"\$\@\" | sed -e '/^$filter_provides[0]\$/d'";
        if (@filter_provides > 1) {
            for my $dep (@filter_provides[1..$#filter_provides]) {
                print $sh " \\\n    -e '/^$dep\$/d'";
            }
        }
        print $sh "\n";
    }

    my $spec_name = "$prefix$name";
    my $spec_basename = "$spec_name.spec";
    my $spec_dir = '.';
    if ($use_outdir) {
        $spec_dir = "$outdir/$spec_name";
        mkdir_p($spec_dir) if (!-d $spec_dir);
    }
    my $specfile = ($spec_dir eq '.' ? $spec_basename : "$spec_dir/$spec_basename");
    verbose "Writing $specfile...";

    my $spec;
    if ($force) {
        rename($specfile, "$specfile~") if (-e $specfile);
        $spec=new FileHandle ">$specfile";
    } else {
        $spec=new FileHandle "$specfile", O_WRONLY|O_CREAT|O_EXCL;
    }

    if (!$spec) {
        warn "Failed to create $specfile: $!\n";
        next;
    }

    print $spec qq[\%{!?perl_$vendorlib: \%define perl_$vendorlib \%(eval "\`perl -V:install$vendorlib\`"; echo \$install$vendorlib)}\n\n]
        if ($compat);

    my $license="";

    my $scripts=0;
    my (%build_requires,%requires);
    my ($yml,$meta);
    if (grep /^META\.yml$/, @files
        and $yml=extract($archive, $type, "$path/META.yml")) {
        # Basic idea borrowed from Module::Depends.
        my $meta;
        eval { $meta=Load($yml); };
        if ($@) {
            warn "Error parsing $path/META.yml: $@";
            goto SKIP;
        }

        %build_requires=%{$meta->{build_requires}} if ($meta->{build_requires});
        %requires=%{$meta->{requires}} if ($meta->{requires});
        if ($meta->{recommends}) {
            for my $dep (keys(%{$meta->{recommends}})) {
                $requires{$dep}=$requires{$dep}
                    || $meta->{recommends}->{$dep};
            }
        }

        # FIXME - I'm not sure this is sufficient...
        if ($meta->{script_files} or $meta->{scripts}) {
            $scripts=1;
        }

        if ($meta->{license}) {
            # This list of licenses is from the Module::Build::API
            # docs, cross referenced with the list of licenses in
            # /usr/share/rpmlint/config.
            if ($meta->{license} =~ /^perl$/i) {
                $license="GPL-1.0-or-later OR Artistic-1.0-Perl";
            } elsif ($meta->{license} =~ /^apache$/i) {
                $license="Apache-2.0";
            } elsif ($meta->{license} =~ /^artistic$/i) {
                $license="Artistic-1.0-Perl";
            } elsif ($meta->{license} =~ /^artistic_?2$/i) {
                $license="Artistic-2.0";
            } elsif ($meta->{license} =~ /^bsd$/i) {
                $license="BSD";
            } elsif ($meta->{license} =~ /^gpl$/i) {
                $license="GPL-1.0-or-later";
            } elsif ($meta->{license} =~ /^lgpl$/i) {
                $license="LGPL-2.0-or-later";
            } elsif ($meta->{license} =~ /^mit$/i) {
                $license="MIT";
            } elsif ($meta->{license} =~ /^mozilla$/i) {
                $license="MPL-1.0";
            } elsif ($meta->{license} =~ /^open_source$/i) {
                $license="any-OSI"; # rpmlint will complain
            } elsif ($meta->{license} =~ /^unrestricted$/i) {
                $license="Distributable";
            } elsif ($meta->{license} =~ /^restrictive$/i) {
                $license="Non-distributable";
                warn "[$module] License is 'restrictive'."
                    . "  This package should not be redistributed.\n";
            } else {
                warn "[$module] Unknown license '" . $meta->{license} . "' in $name!\n";
                $license="CHECK(Distributable)";
            }
        }
        SKIP:
    }

    if (my @licenses=grep /license|copyright|copying/i, @doc) {
        if (!$license) {
            $license="Distributable, see @licenses";
        } elsif ($license=~/^(OSI-Approved|Distributable|Non-distributable)$/) {
            $license.=", see @licenses";
        }
    }

    $license=refine_license_from_files(
        archive       => $archive,
        type          => $type,
        path          => $path,
        files         => \@files,
        license_files => \@license,
        current       => $license,
    );

    # Normalize redundant GPL/LGPL alternatives produced by file scanning.
    #
    # Some source texts mention both a broad form and a narrow form for the
    # same license family and version, for example:
    #
    #   LGPL-2.0-or-later OR LGPL-2.0-only
    #
    # The "or-later" form already covers the same version and later versions,
    # so keeping the matching "only" term only makes the generated License tag
    # noisier.  This block only cleans up an already-detected expression; it
    # does not infer any new license and does not touch CHECK(...) values.
    if ($license !~ /^CHECK\(/) {
        my @terms = split /\s+OR\s+/, $license;
        my %has_or_later;

        for my $term (@terms) {
            if ($term =~ /^(GPL|LGPL)-(\d+(?:\.\d+)?)-or-later$/) {
                $has_or_later{"$1-$2"} = 1;
            }
        }

        my @kept;
        my %seen;
        for my $term (@terms) {
            if ($term =~ /^(GPL|LGPL)-(\d+(?:\.\d+)?)-only$/
                and $has_or_later{"$1-$2"}) {
                next;
            }

            next if ($seen{$term}++);
            push @kept, $term;
        }

        $license = join(' OR ', @kept);
    }

    my $usebuildpl=0;
    if (grep /^Build\.PL$/, @files) {
        $build_requires{'Module::Build'}=0;
        $usebuildpl=1;
    } else {
        $build_requires{'ExtUtils::MakeMaker'}=0;
    }

    if (!$usebuildpl) {
        # This is an ugly hack to parse any PREREQ_PM in Makefile.PL.
        if (open(CHILD, "-|") == 0) {
            eval {
                use subs 'WriteMakefile';

                sub WriteMakefile(@) {
                    my %args=@_;

                    if (!defined($args{'PREREQ_PM'})) {
                        return;
                    }

                    # Versioned BuildRequires aren't reliably honored by
                    # rpmbuild, but we'll include them anyway as a hint to the
                    # packager.
                    for my $dep (keys(%{$args{'PREREQ_PM'}})) {
                        print "BuildRequires: $dep";
                        print " " . $args{'PREREQ_PM'}->{$dep}
                            if ($args{'PREREQ_PM'}->{$dep});
                        print "\n";
                    }
                }
            };

            local $/=undef;

            my $makefilepl=extract($archive, $type, "$path/Makefile.PL")
                or warn "Failed to extract $path/Makefile.PL";

            open(STDIN, ">/dev/null");
            open(STDERR, ">/dev/null");
            eval "no warnings;
                  use subs qw(require die warn eval open close rename);
                  BEGIN { sub require { 1; } }
                  BEGIN { sub die { 1; } }
                  BEGIN { sub warn { 1; } }
                  BEGIN { sub eval { 1; } }
                  BEGIN { sub open { 1; } }
                  BEGIN { sub close { 1; } }
                  BEGIN { sub rename { 1; } }
                  $makefilepl";

            exit 0;
        } else {
            while (<CHILD>) {
                if (/^BuildRequires:\s*(\S+)\s*(\S+)?/) {
                    my $dep=$1;
                    my $version=0;
                    $version=$2 if (defined($2));
                    $build_requires{$dep}=$version;
                }
            }
        }
    }

    print $spec <<END;
Name:           $prefix$name
Version:        $version
Release:        %autorelease
END

    print $spec "Epoch:          $epoch\n" if (defined($epoch));

    print $spec <<END;
Summary:        $summary
License:        $license
URL:            $url
#!RemoteAsset:  sha256:@{[$sha256 ? $sha256 : ""]}
Source0:        $source
END

    printf $spec "%-16s%s\n", "BuildArch:", "noarch" if ($noarch);
    print $spec "\n";

    #
    # For most perl modules need generators, hard code here.
    # This package (perl-rpm-packaging) is not a perl module,
    # It provides some commands, need to use the native name
    # of the packages
    #

    if (! $usebuildpl) {
        printf $spec "%-16s%s\n", "BuildRequires:", 'make';
    }
    printf $spec "%-16s%s\n", "BuildRequires:", "perl-rpm-packaging";
    printf $spec "%-16s%s\n", "BuildRequires:", "perl-macros";

    if (defined($requires{perl})) {
        $build_requires{perl}=$build_requires{perl} || $requires{perl};
        delete $requires{perl};
    }

    # We just keep the code for backward compatibility. - 251
    if (defined($build_requires{perl})) {
        $build_requires{perl} =~ s/^[<>=]+ *//;

        # Convert decimal version to dotted
        if ($build_requires{perl} =~ /^v?(\d+)\.(\d{3})(\d{3})?/) {
            $build_requires{perl} = int($1).'.'.int($2);
            if ($3) {
                $build_requires{perl} .= '.'.int($3);
            } else {
                $build_requires{perl} .= '.0';
            }

        # Remove 'v' on begin
        } elsif ($build_requires{perl} =~ m/^v(.*)$/ms) {
            $build_requires{perl} = $1;
        }

        printf $spec "%-16s%s >= %s\n", "BuildRequires:", "perl", $build_requires{perl}
            if $build_requires{perl};
        delete $build_requires{perl};
    }

    for my $dep (keys(%requires)) {
        $build_requires{$dep}=$build_requires{$dep} || $requires{$dep};
    }

    for my $dep (sort(keys(%build_requires))) {
        if (exists($corelist{$dep})) {
            next if (!$compat);
        } elsif ($follow) {
            if ($dep ne $module and !(grep { $_ eq $dep } @processed, @args)) {
                if (check_dep($dep)) {
                    verbose("$dep is available, skipping.");
                } else {
                    verbose("$dep is not available, adding it to the list.");
                    push(@args, $dep);
                }
            }
        }
        printf $spec "%-16s%s", "BuildRequires:", "perl($dep)";
        print $spec (" >= " . $build_requires{$dep})
            if ($build_requires{$dep});
        print $spec "\n";
    }

    for my $dep (@add_buildrequires) {
        printf $spec "%-16s%s\n", "BuildRequires:", $dep;
    }
    # Only add a separating blank line if we will actually print
    # any Requires or Provides entries next.
    my $will_print_requires = 0;
    for my $dep (keys(%requires)) {
        next if (!$compat and exists($corelist{$dep}));
        if ($requires{$dep}) { $will_print_requires = 1; last; }
    }
    my $will_print_add_requires = scalar(@add_requires) ? 1 : 0;
    my $will_print_add_provides = scalar(@add_provides) ? 1 : 0;

    if ($will_print_requires || $will_print_add_requires || $will_print_add_provides) {
        print $spec "\n";
    }

    for my $dep (sort(keys(%requires))) {
        next if (!$compat and exists($corelist{$dep}));
        if ($requires{$dep}) {
            printf $spec "%-16s%s", "Requires:", "perl($dep)";
            print $spec (" >= " . $requires{$dep});
            print $spec "\n";
        }
    }

    for my $dep (@add_requires) {
        printf $spec "%-16s%s\n", "Requires:", $dep;
    }

    for my $prov (@add_provides) {
        printf $spec "%-16s%s\n", "Provides:", $prov;
    }

    if (@filter_requires) {
        print $spec <<END;

Source98:       $name-filter-requires.sh
\%global real_perl_requires \%{__perl_requires}
\%define __perl_requires \%{_tmppath}/\%{name}-\%{version}-\%{release}-\%(\%{__id_u} -n)-filter-requires
END
    }

    if (@filter_provides) {
        print $spec <<END;

Source99:       $name-filter-provides.sh
\%global real_perl_provides \%{__perl_provides}
\%define __perl_provides \%{_tmppath}/\%{name}-\%{version}-\%{release}-\%(\%{__id_u} -n)-filter-provides
END
    }

    my $buildpath=$path;
    $buildpath=~s/$version/\%{version}/;
    print $spec <<END;

\%description
$description

\%prep
\%setup -q@{[($noprefix ? "" : " -n $buildpath")]}
END

    if (@filter_requires) {
        print $spec <<'END';

sed -e 's,@@PERL_REQ@@,%{real_perl_requires},' %{SOURCE98} > %{__perl_requires}
chmod +x %{__perl_requires}
END
    }

    if (@filter_provides) {
        print $spec <<'END';

sed -e 's,@@PERL_PROV@@,%{real_perl_provides},' %{SOURCE99} > %{__perl_provides}
chmod +x %{__perl_provides}
END
    }

    if (grep { $_ eq "pm_to_blib" } @files) {
        print $spec <<'END';

rm -f pm_to_blib
END
    }

    print $spec <<END;

\%build
END

    if ($usebuildpl) {
        print $spec <<END;
perl Build.PL --installdirs=vendor@{[$noarch ? '' : qq{ optimize="$macro{optimize}"} ]}
./Build
END
    } else {
        print $spec <<END;
perl Makefile.PL INSTALLDIRS=vendor@{[$noarch ? '' : qq{ OPTIMIZE="$macro{optimize}"}]}
END

        print $spec
            "perl -pi -e 's/^\\tLD_RUN_PATH=[^\\s]+\\s*/\\t/' Makefile\n"
            if ($compat and !$noarch);

        print $spec <<END;
%{make_build}
END
    }

    print $spec <<END;

\%install
END

    if ($usebuildpl) {
        print $spec
            "./Build install --destdir=$macro{buildroot} --create_packlist=0\n";
    } else {
        print $spec <<END;
\%perl_make_install
END
    }

    if (!$noarch) {
        print $spec <<END;
find $macro{buildroot} -type f -name '*.bs' -size 0 -exec rm -f {} \\;
END
    }

    print $spec <<END;
\%perl_process_packlist
END

#%{_fixperms} $macro{buildroot}/*

    print $spec <<END;
\%perl_gen_filelist
END

    if ($addlicense and !grep /copying|artistic|copyright|license/i, @doc) {
        print $spec <<END;
perldoc -t perlgpl > COPYING
perldoc -t perlartistic > Artistic

END

        push(@doc, "COPYING", "Artistic");
    }

    print $spec <<END;

\%files -f %{name}.files
\%doc @doc
END

    if ($scripts) {
        print $spec "\%{_bindir}/*\n";
        # FIXME - How do we auto-detect man pages?
    }

    print $spec <<END;

\%changelog
\%autochangelog
END

    $spec->close();

    postprocess_spec($specfile) if (!$skip_postprocess);

    build_rpm($specfile) if ($buildsrpm or $buildrpm);

    push(@processed, $module);
} continue {
    # Best-effort cleanup of downloaded source archive per iteration,
    # even if this iteration used 'next' earlier (e.g., spec file exists).
    if ($cleanup_source && $downloaded) {
        if (-f $file) {
            verbose("Removing downloaded source: $file");
            unlink $file or warn "Failed to remove $file: $!\n";
        }
    }
}

# vi: set ai et:
